apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: caveo-bff
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Custom
      annotations:
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containerConcurrency: 1
      timeoutSeconds: 300
      serviceAccountName: caveo-bff@vitorblsantos.iam.gserviceaccount.com
      containers:
        - image: us.gcr.io/vitorblsantos/caveo-bff:latest
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: APP_PORT
              value: '8080'
            - name: APP_URL
              value: 'https://caveo-bff-824385020093.us-central1.run.app'
            - name: CAVEO_DEFAULT_PASSWORD
              value: 'Caveo@2024'
            - name: COGNITO_CLIENT_ID
              value: '1umo3njvmm0cl00ud7hpk3hoog'
            - name: COGNITO_REGION
              value: 'us-east-2'
            - name: COGNITO_USER_POOL_ID
              value: 'us-east-2_DMDaCuZl2'
            - name: NODE_ENV
              value: 'production'
            - name: POSTGRES_DB
              value: 'db_0f1b94ec_cd0c_4580_b791_f9f1ec73c89c'
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_USER
              value: 'u_0f1b94ec_cd0c_4580_b791_f9f1ec73c89c'
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: CAVEO_BFF_POSTGRES_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: CAVEO_BFF_POSTGRES_PASSWORD
            - name: SERVICE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: CAVEO_BFF_SERVICE_ACCOUNT

          resources:
            limits:
              cpu: "2"
              memory: 256Mi
  traffic:
    - percent: 100
      latestRevision: true
