networks:
  caveo-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

services:
  google-pub-sub:
    image: messagebird/gcloud-pubsub-emulator:latest
    container_name: pub-sub
    environment:
      PUBSUB_PROJECT1: "vitorblsantos"
    ports:
      - "8681:8681"
    networks:
      - caveo-network

  pub-sub-ui:
    image: ghcr.io/neoscript/pubsub-emulator-ui:latest
    container_name: pub-sub-ui
    ports:
      - "7200:80"
    networks:
      - caveo-network

  postgres:
    image: postgres:17.1-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: caveo-database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    ports:
      - "5432:5432"
    networks:
      - caveo-network

  caveo-bff:
    build:
      args:
        NODE_ENV: "production"
      context: .
      dockerfile: Dockerfile
    container_name: caveo-bff
    environment:
      APP_PORT: 8080
      NODE_ENV: production
      POSTGRES_DB: caveo-database
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
    image: us.gcr.io/vitorblsantos/caveo-bff:latest
    networks:
      - caveo-network
    ports:
      - "8080:8080"
    restart: on-failure
