CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(50) NOT NULL,
  name VARCHAR(50) NOT NULL,
  status VARCHAR(20),
  role VARCHAR(10),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
