CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(50) NOT NULL,
  isOnboarded BOOLEAN DEFAULT false,
  name VARCHAR(50) NOT NULL,
  role VARCHAR(10),
  status VARCHAR(20),
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  deletedAt TIMESTAMP WITH TIME ZONE DEFAULT,
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
